apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    name: nginx-cm
spec:
  containers:
  - name: nginx-cm
    image: nginx:latest
    ports:
      - containerPort: 8888
    volumeMounts:
    - name: conf
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: conf
    configMap:
      name: nginx-cm
      items:
      - key: nginx-custom-config.conf
        path: default.conf

  
